app:
  categoryMatchers:
    #Day to day
    - categoryId: GROCERIES
      details: Fruit lovers market, Checkers and Spar
      regex: (Flm)|(Checkers)|(Spar)|(Pnp)|(Woolworths)|(Compass Group Sa)
      priority: 0
    - categoryId: TRANSPORT
      details: Transport and Fuel
      regex: (Uber)|(BP)|(Total)|(Engen)|(Caltex)
      priority: 10
    - categoryId: TAKEOUT
      details: Eating Out & Takeouts
      regex: ((?i)(kfc)|(WIMPY)|(Debonairs)|(Burger King)|(spur)|(mcd)|(Seattle)|(Romans Pizza)|(Mimmos)|(Ugly Delicious Food Co)|(Dakota Steak Ranch)|(Salsa)|(Rocco Mama's))
      priority: 12
    - categoryId: HEALTH
      details: Healh & Medical
      regex: ((?i)(clicks)|(dis(-|)chem)|(sportsmans)|(Cricket))
      priority: 13
    - categoryId: ALCOHOL
      details: Alcohol
      regex: ((?i)(.*liqour.*)|(.*bottle.*)|(tops))
      priority: 14
    - categoryId: GENERAL_PURCHASES
      details: General purchases
      regex: (Takealot)|(Evetech)|(Computicket)
      priority: 15
    - categoryId: ATM_DRAW
      details: Drawing money from atm
      type: Atm Cash
      priority: 16
    #Recurring
    - categoryId: ENTERTAINMENT
      details: Media
      regex: ((?i)(Google)|(Steamgames.*)|(Netflix.*)|(Spotifyza)|(G2a.*)|(bowling)|(origin.*)|(Epc\*epic)|(Molly Malones))
      priority: 20
    - categoryId: INTERNET_PHONE
      details: Internet and phone
      regex: (cool Ideas)|(Vodacom)|(Afrihost.*)
      priority: 21
    - categoryId: RENT
      details: Monthly rent
      regex: (?i)rent
      priority: 22
    - categoryId: INSURNACE
      details: Insurance
      regex: (Miwaycolle\d+)|(Discinsure\d+)|(Ium Prem)
      priority: 23
    - categoryId: VEHICLE_INSTALLMENT
      details: Vehicle Repayments
      regex: Ned/.+
      priority: 24
    - categoryId: DEBT_PAYMENT
      details: Debt repayment
      regex: (?i)payoff
      priority: 25
    - categoryId: BANK_FEES
      details: Bank Charges & Fees
      regex: (Monthly Account Fee)|(Vitality Money Premium)|(Real-time Payment Fee)
      priority: 26
    - categoryId: SAVINGS
      details: Monthly savings
      regex: (Save)
      priority: 27
    #Income
    - categoryId: SALARY
      details: Monthly salary
      regex: Disc \d+
      priority: 40
      isPositive: true
    - categoryId: INTEREST
      details: Interest
      regex: (Interest Earned)|(Dynamic Interest)
      priority: 41
    #DEFAULT
    - categoryId: UNCATEGORISED
      details: Uncategorised day to day
      regex: .*
      lessThan: 1
      priority: 99
    - categoryId: UNCATEGORISED_INCOME
      details: Uncategorised income
      regex: .*
      greaterThan: 0
      priority: 100

  groups:
    - id: DAY_TO_DAY
      name: Day to day
    - id: RECURRING
      name: Recurring
    - id: INCOME
      name: Income

  categories:
    - id: UNCATEGORISED
      groupId: DAY_TO_DAY
      name: Uncategorised
      budgeted: 2000
    - id: UNCATEGORISED_INCOME
      groupId: INCOME
      name: Uncategorised
      budgeted: 200
    - id: GROCERIES
      groupId: DAY_TO_DAY
      name: groceries
      budgeted: 1500
    - id: ATM_DRAW
      groupId: DAY_TO_DAY
      name: Atm cash
      budgeted: 200
    - id: GENERAL_PURCHASES
      groupId: DAY_TO_DAY
      name: General purchases
      budgeted: 500
    - id: TRANSPORT
      groupId: DAY_TO_DAY
      name: Transport & Fuel
      budgeted: 1400
    - id: TAKEOUT
      groupId: DAY_TO_DAY
      name: Takeout
      budgeted: 1000
    - id: HEALTH
      groupId: DAY_TO_DAY
      name: Health
      budgeted: 200
    - id: ALCOHOL
      groupId: DAY_TO_DAY
      name: Alcohol
      budgeted: 200
    - id: INTERNET_PHONE
      groupId: RECURRING
      name: Internet & Phone
      budgeted: 2048
    - id: ENTERTAINMENT
      groupId: DAY_TO_DAY
      name: Entertainment
      budgeted: 1000
    - id: RENT
      groupId: RECURRING
      name: Rent
      budgeted: 2000
    - id: INSURNACE
      groupId: RECURRING
      name: Insurance
      budgeted: 2038
    - id: VEHICLE_INSTALLMENT
      groupId: RECURRING
      name: Vehicle Installment
      budgeted: 5700
    - id: DEBT_PAYMENT
      groupId: RECURRING
      name: Debt Payment
      budgeted: 200
    - id: BANK_FEES
      groupId: RECURRING
      name: Bank Fees
      budgeted: 200
    - id: SAVINGS
      groupId: RECURRING
      name: Savings
      budgeted: 2000
    - id: SALARY
      groupId: INCOME
      name: Salary
      budgeted: 23049.41
    - id: INTEREST
      groupId: INCOME
      name: Interest
      budgeted: 200